- name: Download repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Copy service file
  ansible.builtin.template:
    src: docker.service
    dest: /etc/systemd/system/multi-user.target.wants/docker.service

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Get Runner Token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/raghudevopsb84/actions/runners/registration-token | jq .token | xargs
  delegate_to: localhost
  register: gh_org_token

- name: Create Runner Containers
  loop:
    - runner-1
    - runner-2
    - runner-3
  community.docker.docker_container:
    name: "{{ item }}"
    image: rkalluru/d84-github-runner
    pull: always
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: true
    restart_policy: always
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:ORG token={{ token }} url=http://vault-int.rdevopsb84.online:8200') }}"
      TOKEN: "{{ gh_org_token.stdout }}"
      NAME: "{{ item }}"
      ARM_CLIENT_ID:  "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_ID token={{ token }} url=http://vault-int.rdevopsb84.online:8200') }}"
      ARM_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_SECRET token={{ token }} url=http://vault-int.rdevopsb84.online:8200') }}"
      ARM_TENANT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_TENANT_ID token={{ token }} url=http://vault-int.rdevopsb84.online:8200') }}"


